name: Trigger deploy on a schedule if changes occurred since last deploy

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check_deploy_required:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Determine if last change date within 24 hours
        run: |
          npm install contentful

          LAST_COMMIT=$(git show --no-patch --format=%ct HEAD)
          LAST_CTFL_CHANGE=$(node ./.github/scripts/get-latest-contentful-entry.js)

          CURRENT_TS=$(date +%s)
          DAY_SEC=$((24 * 60 * 60))
          DATE_24HRS_AGO=$(($CURRENT_TS - $DAY_SEC))

          [ $LAST_COMMIT -ge $DATE_24HRS_AGO -o $LAST_CTFL_CHANGE -ge $DATE_24HRS_AGO ] && result="Y" || result="N"

          echo "Last change within 24 hours? $result"
          echo "required=$result" >> $GITHUB_OUTPUT
        env:
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}

  deploy:
    needs: check_deploy_required
    if: ${{ needs.check_deploy_required.outputs.required }} == 'Y'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build:prod
        env:
          CI: true
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
